apiVersion: v1
kind: Service
metadata:
    name: "bgbrt-0f7b"
    labels:
        app: "bgbrt-0f7b"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "bgbrt-0f7b"